# Generated by Django 2.2.6 on 2019-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prothomalo', '0003_auto_20191006_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
