# Generated by Django 2.2.6 on 2019-10-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prothomalo', '0004_auto_20191007_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
