# Generated by Django 2.2.6 on 2019-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prothomalo', '0005_news_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
