# Generated by Django 2.2.6 on 2019-10-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prothomalo', '0006_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Newses'},
        ),
    ]
