# Generated by Django 2.2.6 on 2019-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prothomalo', '0007_auto_20191007_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
