# Generated by Django 2.2.6 on 2019-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prothomalo', '0009_auto_20191009_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
