# Generated by Django 2.2.6 on 2019-10-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalerkantho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Newses'},
        ),
    ]
