# Generated by Django 2.2.6 on 2019-10-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalerkantho', '0005_news_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
