# Generated by Django 2.2.6 on 2019-10-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
